[package]
name = "solana-sdk"
description = "Solana SDK"
documentation = "https://docs.rs/solana-sdk"
readme = "README.md"
version = "1.18.12"
edition = "2021"

[features]
# "program" feature is a legacy feature retained to support v1.3 and older
# programs.  New development should not use this feature.  Instead use the
# solana-program crate
program = []

default = [
  "full", # functionality that is not compatible or needed for on-chain programs
]
full = [
  "assert_matches",
  "byteorder",
  "chrono",
  "generic-array",
  "memmap2",
  "rand",
  "rand0-7",
  "serde_json",
  "ed25519-dalek",
  "ed25519-dalek-bip32",
  "solana-logger",
  "libsecp256k1",
  "sha3",
  "digest",
]
dev-context-only-utils = []

[dependencies]
assert_matches = { version = "1.5.0", optional = true }
base64 = { version = "0.21.7" }
bincode = { version = "1.3.3" }
bitflags = { version = "2.4.2" }
borsh = { version = "1.2.1" }
bs58 = { version = "0.4.0" }
bytemuck = { version = "1.14.0", features = ["derive"] }
byteorder = { version = "1.5.0", optional = true }
chrono = { version = "0.4.31", features = ["alloc"], optional = true }
curve25519-dalek = { version = "4.1.2", optional = true }
derivation-path = { version = "0.2.0" }
digest = { version = "0.10.7", optional = true }
ed25519-dalek = { version = "2.1.1", optional = true }
ed25519-dalek-bip32 = { version = "0.3.0", optional = true }
generic-array = { version = "0.14.7", features = [
  "serde",
  "more_lengths",
], optional = true }
hmac = { version = "0.12.1" }
itertools = { version = "0.10.5" }
lazy_static = { version = "1.4.0" }
libsecp256k1 = { version = "0.6.0", optional = true }
log = { version = "0.4.20" }
memmap2 = { version = "0.5.10", optional = true }
num-derive = { version = "0.4" }
num-traits = { version = "0.2" }
num_enum = { version = "0.4" }
pbkdf2 = { version = "0.11.0", default-features = false }
qstring = { version = "0.7.2" }
qualifier_attr = { version = "0.2.2" }
rand = { version = "0.8.5", optional = true }
rand0-7 = { package = "rand", version = "0.7", optional = true }
rustversion = { version = "1.0.14" }
serde = { version = "1.0.195" }
serde_bytes = { version = "0.11.14" }
serde_derive = { version = "1.0.103" }
serde_json = { version = "1.0.111", optional = true }
serde_with = { version = "2.3.3", default-features = false, features = [
  "macros",
] }
sha2 = { version = "0.10.8" }
sha3 = { version = "0.10.4", optional = true }
siphasher = { version = "0.3.11" }
solana-frozen-abi = { version = "1.18.12" }
solana-frozen-abi-macro = { version = "1.18.12" }
solana-logger = { version = "1.18.12", optional = true }
solana-program = { version = "1.18.12", path = "./program" }
solana-sdk-macro = { version = "1.18.12" }
thiserror = { version = "1.0.56" }
uriparse = { version = "0.6.4" }
wasm-bindgen = { version = "0.2" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { version = "0.3.67" }

[dev-dependencies]
anyhow = { version = "1.0.79" }
curve25519-dalek = { version = "4.1.2" }
hex = { version = "0.4.3" }
solana-sdk = { path = ".", features = ["dev-context-only-utils"] }
static_assertions = { version = "1.1.0" }
tiny-bip39 = { version = "0.8.2" }

[build-dependencies]
rustc_version = { version = "0.4" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]
