[package]
name = "conjunto_addresses"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
paste = { workspace = true }
solana-sdk = { workspace = true }
