name: Build+Test+Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Conjunto
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: conjunto

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CARGO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'conjunto-build_test_lint-cache-bust-000'
          workspaces: |
            conjunto -> target
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true

      - name: Prebuild Conjunto Target Size
        run: du -h -d1 conjunto/target || true

      - name: Cargo Build
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          make ci-build
        shell: bash
        working-directory: conjunto

      - name: Cargo Clippy Lint
        run: make ci-clippy
        shell: bash
        working-directory: conjunto

      - name: Cargo Test
        run: make ci-test
        shell: bash
        working-directory: conjunto

      - name: Postbuild Conjunto Target Size
        run: du -h -d1 conjunto/target
